pub mod iroh_net;
pub mod config;
pub mod discovery;
pub mod transfer;
pub mod protocol;
pub mod auth;
pub mod compression;
pub mod tls;
pub mod stun;
pub mod hole_punch;
pub mod message_store;
pub mod signal_client;

pub use config::{Config, generate_random_name};
pub use discovery::{DiscoveryService, Device};
pub use transfer::{TransferService, scan_directory, calculate_total_size, count_files, ProgressTracker, TransferProgress, TransferRecord, HistoryStore, ShareEntry, ShareStore, BookmarkEntry, BookmarkStore, compute_file_sha256};
pub use auth::AuthManager;
pub use compression::Compressor;
pub use tls::TlsManager;
pub use stun::{StunClient, NatType};
pub use hole_punch::{UdpHolePuncher, HolePunchRequest, HolePunchResponse};
pub use message_store::{MessageStore, ChatMessage, ConversationDelta};
pub use signal_client::{SignalClient, FriendInfo, SignalStatus};
pub use iroh_net::IrohManager;
