pub mod config;
pub mod discovery;
pub mod transfer;
pub mod protocol;
pub mod auth;
pub mod compression;
pub mod tls;
pub mod stun;
pub mod hole_punch;
pub mod message_store;

pub use config::Config;
pub use discovery::{DiscoveryService, Device};
pub use transfer::{TransferService, scan_directory, calculate_total_size, count_files, ProgressTracker, TransferProgress};
pub use auth::AuthManager;
pub use compression::Compressor;
pub use tls::TlsManager;
pub use stun::{StunClient, NatType};
pub use hole_punch::{UdpHolePuncher, HolePunchRequest, HolePunchResponse};
pub use message_store::{MessageStore, ChatMessage};
